# Generated by Django 4.1 on 2023-08-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowersbunch',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flowersbunch',
            name='reason',
        ),
        migrations.AlterField(
            model_name='flowersbunch',
            name='composition',
            field=models.TextField(blank=True, verbose_name='цветочный состав букета'),
        ),
        migrations.AlterField(
            model_name='flowersbunch',
            name='description',
            field=models.TextField(blank=True, verbose_name='смысл букета'),
        ),
    ]
