# Generated by Django 4.1 on 2023-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_remove_flowersbunch_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowersbunch',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендован'),
        ),
    ]
