# Generated by Django 4.1 on 2023-08-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_flowersbunch_recommended'),
        ('webshop', '0003_lead_called_at_lead_created_at'),
    ]

    operations = [
    ]
