# Generated by Django 4.1 on 2023-08-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_merge_20230818_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowersbunch',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bunchs', to='webshop.categoryprice', verbose_name='ценовая категория'),
        ),
        migrations.AddField(
            model_name='flowersbunch',
            name='reason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bunchs', to='webshop.reason', verbose_name='повод для букета'),
        ),
    ]
