# Generated by Django 4.1 on 2023-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_flowersbunch_category_flowersbunch_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordertime',
            field=models.CharField(blank=True, db_index=True, default='Как можно скорее', max_length=50, verbose_name='Интервал доставки'),
        ),
    ]
